title: md-content-factory
markdown: kramdown
baseurl: md-content.js
highlighter: rouge
permalink: pretty
kramdown:
  input: GFM
  toc_levels: 1..3
  hard_wrap: false
  syntax_highlighter: rouge
plugins: []
